name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build plugin
        run: npm run build
        
      - name: Create release zip
        run: |
          mkdir obsidian-oreilly-learning-plugin
          cp main.js manifest.json styles.css obsidian-oreilly-learning-plugin/
          zip -r obsidian-oreilly-learning-plugin.zip obsidian-oreilly-learning-plugin
        
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            obsidian-oreilly-learning-plugin.zip